### PR TITLE
BepInEx support & better build script

### PR DESCRIPTION
**Pull request by RedstoneWizard08**
This allows us to use SpaceWarp alongside other BepInEx-based mods, and also creates a better build script.

The build script will:
- Automatically build the project
- Copy the required files
- Compress everything into release binaries
- Build targets for both BepInEx and Doorstop

The BepInEx loader literally is just a wrapper that calls the Doorstop entrypoint so it's easier to maintain. You can look at it, its at `SpaceWarp/BepInExEntrypoint.cs`

### CODE REVIEW

**Comment by cheese3660** [comment]
This looks good, I'm wondering, what is your discord?

**Comment by RedstoneWizard08** [comment]
RedstoneWizard08#5808

**Comment by cheese3660** [comment]
Ah, thats why I couldn't ping to ask about this.
Looks good as I said, just gonna ask the obvious? It's been tested both with BepInEx and standalone?

**Comment by RedstoneWizard08** [comment]
I've tested BepInEx, after I eat lunch I'll test standalone. Theoretically it should work. Can confirm BepInEx is working.

**Comment by RedstoneWizard08** [comment]
I opened up the assemblies in DnSpyEx and the preprocessor directives are working - granted you use the build script.

**Comment by cheese3660** [comment]
Confirmed working by contributor, accepting

**Pull request merged**
